### ISSUE TITLE
Could You Provide The App backend code too 

### ISSUE THREAD

**Issue by engineeringstudent0012** [shockbytes/Corey#27]
Due to me and my family getting Corona virus and being in the  hospital for about 3 months because of post Coronavirus complication due to which my brother nearly died  I couldn't finish my Major Project and my presentation is in a week and I can't make an app within a week and I don't show them the code I need to a year loss. As I hade made a proposal of Fitness app your application will do.

So, could you give me the backend code or mail this app Apk [engineeringstudent0012gmail.com] . So, I could show the app to examiner and I will show source code in android studio. 

I don't intend to publish or distribute this app in anyway just that got into trouble due to getting Covid. 

Please could you help me this once, I will be always grateful for you.

Yours Sincerely,
Aasutosh Khadka

**Comment by shockbytes** [comment]
Hello @engineeringstudent0012!

That's sad to hear. Unfortunately, there is not much I can help you with. There is actually no backend code, it's all running on Firebase. I think you managed to connect already your Firebase account to the project.

I think the app is crashing all the time because you have to connect it to your Google Fit app too. You gotta have to setup your Google Fit app and enter your height and weight in the Google Fit app. That should be basically everything that you need to do to make it work.

Hope that helps. If not, you can reach out to me via mail. Just drop a mail at shockbytesstudio@gmail.com in case something isn't working.

Best regards,
Martin

**Comment by shockbytes** [comment]
Discussed via mail. Closing this issue for now.
